" General settings

syntax enable			  " Highlight Syntax

set softtabstop=2		  " 2 space tabs
set showcmd			  " Display incomplete commands
set showmode			  " Show the vim mode
set number			  " Show line numbers
set ruler			  " Show cursor position

set backspace=indent,eol,start	  " Intuitive backspacing
